name: Echo

on:
  push:
    paths-ignore:
      - "README.md"

env:
  REPO: actions-test
  # MSG: ${{ REPO }}

jobs:
  # echo:
  #   runs-on: ubuntu-18.04

  #   steps:
  #     - run: |
  #         echo REPO
  #         echo $MSG

  env-to-env:
    runs-on: ubuntu-latest

    steps:
      - run: echo $ENV
        env:
          ENV: $REPO
