name: Echo

on:
  push:
    paths-ignore:
      - 'README.md'


env:
  REPO: actions-test
  MSG: ${{ REPO }}

jobs:
  echo:
    runs-on: ubuntu-18.04

    steps:
      - run: |
          echo REPO
          echo $MSG
