name: Go-test

on:
  push:
    branches:
      - "master"
    paths:
      - ".github/workflows/go_test.yml"
      - "go/**"

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: go
    steps:
      - uses: actions/checkout@v2

      - name: Set up Go 1.14
        uses: actions/setup-go@v2
        with:
          go-version: 1.14

      - name: Get dependencies
        run: go get -v

      - name: Test code
        run: go test -v ./...
